name: velha_guarda
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flip_card: ^0.4.4


  cupertino_icons: ^0.1.2
  fluttery_dart2: ^0.0.9
  provider: ^3.0.0+1
  intl:
  flutter_staggered_grid_view: ^0.2.7
  cloud_firestore: ^0.11.0+2
  carousel_pro: ^0.0.13
  transparent_image: ^1.0.0
  scoped_model: ^1.0.1
  firebase_auth: ^0.11.1
  url_launcher: ^5.0.2
  flutter_launcher_icons: ^0.7.2
  image_picker: ^0.6.0+3
  flare_flutter: 2.0.3
  bloc_pattern: ^1.5.2
  rxdart: ^0.22.0
  shimmer: ^1.0.0
  rflutter_alert: ^1.0.2
  flutter_bloc: ^0.15.0
  equatable: ^0.2.0
  flutter_timer: 0.0.5
  wave: ^0.0.8
  flutter_svg: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - images/
    - assets/
    - fonts/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

    - family: Qwigley
      fonts:
        - asset: fonts/qwigley/Qwigley-Regular.ttf

    - family: Dosis
      fonts:
        - asset: fonts/dosis/Dosis-Regular.otf
          weight: 400
        - asset: fonts/dosis/Dosis-Medium.otf
          weight: 500
        - asset: fonts/dosis/Dosis-SemiBold.otf
          weight: 600
        - asset: fonts/dosis/Dosis-Bold.otf
          weight: 800
        - asset: fonts/dosis/Dosis-ExtraBold.otf
          weight: 900
    - family: U and I
      fonts:
        - asset: fonts/fontYouandiModernTR.ttf
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
